<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-09T20:06:23+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.full_page_lifetime_value
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
    'debug' => [
        'display_errors' => true,
        'detail' => 'debug',
        'error_reporting' => null,
    ],
    'misc' => [
        'do_page_reindex_check' => false,
        'latest_version' => '8.5.2',
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => false,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
