<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-01-30T22:42:42+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
    'debug' => [
        'display_errors' => true,
        'detail' => 'debug',
        'error_reporting' => null,
    ],
    'misc' => [
        'do_page_reindex_check' => true,
    ],
];
