<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-03-18T14:33:09+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
    'debug' => [
        'display_errors' => true,
        'detail' => 'debug',
        'error_reporting' => null,
    ],
    'misc' => [
        'do_page_reindex_check' => false,
        'latest_version' => '8.5.2',
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
];
