<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-12-17T20:09:39+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'M and H Property Services',
        ],
    ],
];
