<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-09T13:11:39+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      connections.concrete
 * @group     database
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'default-connection' => 'concrete',
    'connections' => [
        'concrete' => [
            'driver' => 'c5_pdo_mysql',
            'server' => 'localhost',
            'database' => 'mandhpropertyservices_com',
            'username' => 'root',
            'password' => '',
            'character_set' => 'utf8',
            'collation' => 'utf8_bin',
        ],
    ],
];
